name: pylint-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Randomly hitting TypeError: object int can't be used in 'await' expression in 3.11
        # So, excluding 3.11 for now
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel cython
        pip install .
        python setup.py build_ext --inplace
    - name: Running unit tests
      run: pytest
    - name: Analysing the code with pylint
      run: pylint --recursive=y nmmo tests
    - name: Looking for xcxc, just in case
      run: |
        if grep -r --include='*.py' 'xcxc'; then
          echo "Found xcxc in the code. Please check the file."
          exit 1
        fi
